%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosFileTransfer_VirtualFileSystem_ContentList
%% Source: /usr/local/src/erlang-otp-r15b01-0.1+imvu/lib/cosFileTransfer/src/CosFileTransfer.idl
%% IC vsn: 4.2.30
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosFileTransfer_VirtualFileSystem_ContentList').
-ic_compiled("4_2_30").


-include("CosFileTransfer_VirtualFileSystem.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_sequence,tk_long,0}.

%% returns id
id() -> "IDL:omg.org/CosFileTransfer/VirtualFileSystem/ContentList:1.0".

%% returns name
name() -> "CosFileTransfer_VirtualFileSystem_ContentList".



