%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosFileTransfer_VirtualFileSystem
%% Source: /usr/local/src/erlang-otp-r15b01-0.1+imvu/lib/cosFileTransfer/src/CosFileTransfer.idl
%% IC vsn: 4.2.30
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSFILETRANSFER_VIRTUALFILESYSTEM_HRL).
-define(COSFILETRANSFER_VIRTUALFILESYSTEM_HRL, true).




-endif.


