%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosTime_TimeUnavailable
%% Source: /usr/local/src/erlang-otp-r15b01-0.1+imvu/lib/cosTime/src/CosTime.idl
%% IC vsn: 4.2.30
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosTime_TimeUnavailable').
-ic_compiled("4_2_30").


-include("CosTime.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosTime/TimeUnavailable:1.0",
                   "TimeUnavailable",[]}.

%% returns id
id() -> "IDL:omg.org/CosTime/TimeUnavailable:1.0".

%% returns name
name() -> "CosTime_TimeUnavailable".



