%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNaming_NamingContextExt_NotEmpty
%% Source: /usr/local/src/erlang-otp-r15b01-0.1+imvu/lib/orber/COSS/CosNaming/cos_naming_ext.idl
%% IC vsn: 4.2.30
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNaming_NamingContextExt_NotEmpty').
-ic_compiled("4_2_30").


-include("CosNaming_NamingContextExt.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosNaming/NamingContext/NotEmpty:1.0",
                   "NotEmpty",[]}.

%% returns id
id() -> "IDL:CosNaming/NamingContextExt/NotEmpty:1.0".

%% returns name
name() -> "CosNaming_NamingContextExt_NotEmpty".



