%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotification_QoSAdmin
%% Source: /usr/local/src/erlang-otp-r15b01-0.1+imvu/lib/cosNotification/src/CosNotification.idl
%% IC vsn: 4.2.30
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFICATION_QOSADMIN_HRL).
-define(COSNOTIFICATION_QOSADMIN_HRL, true).




-endif.


