%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNotifyFilter_CallbackNotFound
%% Source: /usr/local/src/erlang-otp-r15b01-0.1+imvu/lib/cosNotification/src/CosNotifyFilter.idl
%% IC vsn: 4.2.30
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNotifyFilter_CallbackNotFound').
-ic_compiled("4_2_30").


-include("CosNotifyFilter.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosNotifyFilter/CallbackNotFound:1.0",
                   "CallbackNotFound",[]}.

%% returns id
id() -> "IDL:omg.org/CosNotifyFilter/CallbackNotFound:1.0".

%% returns name
name() -> "CosNotifyFilter_CallbackNotFound".



