%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyFilter_Filter
%% Source: /usr/local/src/erlang-otp-r15b01-0.1+imvu/lib/cosNotification/src/CosNotifyFilter.idl
%% IC vsn: 4.2.30
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYFILTER_FILTER_HRL).
-define(COSNOTIFYFILTER_FILTER_HRL, true).




-endif.


