%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTransactions_Control
%% Source: /usr/local/src/erlang-otp-r15b01-0.1+imvu/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.2.30
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTRANSACTIONS_CONTROL_HRL).
-define(COSTRANSACTIONS_CONTROL_HRL, true).




-endif.


