%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyComm_StructuredPushSupplier
%% Source: /usr/local/src/erlang-otp-r15b01-0.1+imvu/lib/cosNotification/src/CosNotifyComm.idl
%% IC vsn: 4.2.30
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCOMM_STRUCTUREDPUSHSUPPLIER_HRL).
-define(COSNOTIFYCOMM_STRUCTUREDPUSHSUPPLIER_HRL, true).




-endif.


