%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventChannelAdmin
%% Source: /usr/local/src/erlang-otp-r15b01-0.1+imvu/lib/cosEvent/src/CosEventChannelAdmin.idl
%% IC vsn: 4.2.30
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCHANNELADMIN_HRL).
-define(COSEVENTCHANNELADMIN_HRL, true).


-record('CosEventChannelAdmin_AlreadyConnected', {'OE_ID'="IDL:omg.org/CosEventChannelAdmin/AlreadyConnected:1.0"}).
-record('CosEventChannelAdmin_TypeError', {'OE_ID'="IDL:omg.org/CosEventChannelAdmin/TypeError:1.0"}).


-endif.


