%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventChannelAdmin_ProxyPullSupplier
%% Source: /usr/local/src/erlang-otp-r15b01-0.1+imvu/lib/cosEvent/src/CosEventChannelAdmin.idl
%% IC vsn: 4.2.30
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCHANNELADMIN_PROXYPULLSUPPLIER_HRL).
-define(COSEVENTCHANNELADMIN_PROXYPULLSUPPLIER_HRL, true).




-endif.


