%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventComm_PushConsumer
%% Source: /usr/local/src/erlang-otp-r15b01-0.1+imvu/lib/cosEvent/src/CosEventComm.idl
%% IC vsn: 4.2.30
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCOMM_PUSHCONSUMER_HRL).
-define(COSEVENTCOMM_PUSHCONSUMER_HRL, true).




-endif.


