%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosEventDomainAdmin_AlreadyExists
%% Source: /usr/local/src/erlang-otp-r15b01-0.1+imvu/lib/cosEventDomain/src/CosEventDomainAdmin.idl
%% IC vsn: 4.2.30
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosEventDomainAdmin_AlreadyExists').
-ic_compiled("4_2_30").


-include("CosEventDomainAdmin.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosEventDomainAdmin/AlreadyExists:1.0",
                   "AlreadyExists",[]}.

%% returns id
id() -> "IDL:omg.org/CosEventDomainAdmin/AlreadyExists:1.0".

%% returns name
name() -> "CosEventDomainAdmin_AlreadyExists".



