%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: erlang
%% Source: /usr/local/src/erlang-otp-r15b01-0.1+imvu/lib/ic/include/erlang.idl
%% IC vsn: 4.2.30
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(ERLANG_HRL).
-define(ERLANG_HRL, true).


-record(erlang_pid, {node, num, serial, creation}).
-record(erlang_port, {node, id, creation}).
-record(erlang_ref, {node, id, creation}).


-endif.


