%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosTransactions_HeuristicRollback
%% Source: /usr/local/src/erlang-otp-r15b01-0.1+imvu/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.2.30
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosTransactions_HeuristicRollback').
-ic_compiled("4_2_30").


-include("CosTransactions.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosTransactions/HeuristicRollback:1.0",
                   "HeuristicRollback",[]}.

%% returns id
id() -> "IDL:omg.org/CosTransactions/HeuristicRollback:1.0".

%% returns name
name() -> "CosTransactions_HeuristicRollback".



