Document: erlang-otp-r15b01
Title: Debian erlang-otp-r15b01 Manual
Author: <insert document author here>
Abstract: This manual describes what erlang-otp-r15b01 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/erlang-otp-r15b01/erlang-otp-r15b01.sgml.gz

Format: postscript
Files: /usr/share/doc/erlang-otp-r15b01/erlang-otp-r15b01.ps.gz

Format: text
Files: /usr/share/doc/erlang-otp-r15b01/erlang-otp-r15b01.text.gz

Format: HTML
Index: /usr/share/doc/erlang-otp-r15b01/html/index.html
Files: /usr/share/doc/erlang-otp-r15b01/html/*.html
