%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: OrberApp_IFR
%% Source: /usr/local/src/erlang-otp-r15b01-0.1+imvu/lib/orber/src/OrberIFR.idl
%% IC vsn: 4.2.30
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(ORBERAPP_IFR_HRL).
-define(ORBERAPP_IFR_HRL, true).




-endif.


