%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTime_TIO
%% Source: /usr/local/src/erlang-otp-r15b01-0.1+imvu/lib/cosTime/src/CosTime.idl
%% IC vsn: 4.2.30
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTIME_TIO_HRL).
-define(COSTIME_TIO_HRL, true).




-endif.


