%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTimerEvent_TimerEventHandler
%% Source: /usr/local/src/erlang-otp-r15b01-0.1+imvu/lib/cosTime/src/CosTimerEvent.idl
%% IC vsn: 4.2.30
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTIMEREVENT_TIMEREVENTHANDLER_HRL).
-define(COSTIMEREVENT_TIMEREVENTHANDLER_HRL, true).




-endif.


