%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: TimeBase
%% Source: /usr/local/src/erlang-otp-r15b01-0.1+imvu/lib/cosTime/src/TimeBase.idl
%% IC vsn: 4.2.30
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(TIMEBASE_HRL).
-define(TIMEBASE_HRL, true).


-record('TimeBase_UtcT', {time, inacclo, inacchi, tdf}).
-record('TimeBase_IntervalT', {lower_bound, upper_bound}).


-endif.


