%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNaming_BindingIterator
%% Source: /usr/local/src/erlang-otp-r15b01-0.1+imvu/lib/orber/COSS/CosNaming/cos_naming.idl
%% IC vsn: 4.2.30
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNAMING_BINDINGITERATOR_HRL).
-define(COSNAMING_BINDINGITERATOR_HRL, true).




-endif.


