%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_cos_naming_ext
%% Source: /usr/local/src/erlang-otp-r15b01-0.1+imvu/lib/orber/COSS/CosNaming/cos_naming_ext.idl
%% IC vsn: 4.2.30
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COS_NAMING_EXT_HRL).
-define(OE_COS_NAMING_EXT_HRL, true).




-endif.


