%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosEventChannelAdmin_TypeError
%% Source: /usr/local/src/erlang-otp-r15b01-0.1+imvu/lib/cosEvent/src/CosEventChannelAdmin.idl
%% IC vsn: 4.2.30
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosEventChannelAdmin_TypeError').
-ic_compiled("4_2_30").


-include("CosEventChannelAdmin.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosEventChannelAdmin/TypeError:1.0",
                   "TypeError",[]}.

%% returns id
id() -> "IDL:omg.org/CosEventChannelAdmin/TypeError:1.0".

%% returns name
name() -> "CosEventChannelAdmin_TypeError".



