%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosEventComm_Disconnected
%% Source: /usr/local/src/erlang-otp-r15b01-0.1+imvu/lib/cosEvent/src/CosEventComm.idl
%% IC vsn: 4.2.30
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosEventComm_Disconnected').
-ic_compiled("4_2_30").


-include("CosEventComm.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosEventComm/Disconnected:1.0","Disconnected",
                   []}.

%% returns id
id() -> "IDL:omg.org/CosEventComm/Disconnected:1.0".

%% returns name
name() -> "CosEventComm_Disconnected".



