%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosPropertyService_ConstraintNotSupported
%% Source: /usr/local/src/erlang-otp-r15b01-0.1+imvu/lib/cosProperty/src/CosProperty.idl
%% IC vsn: 4.2.30
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosPropertyService_ConstraintNotSupported').
-ic_compiled("4_2_30").


-include("CosPropertyService.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosPropertyService/ConstraintNotSupported:1.0",
                   "ConstraintNotSupported",[]}.

%% returns id
id() -> "IDL:omg.org/CosPropertyService/ConstraintNotSupported:1.0".

%% returns name
name() -> "CosPropertyService_ConstraintNotSupported".



